version: "3.9"
 
services:
  web:
    build: ./app
    ports:
      - "${APP_PORT}:5050"
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      WELCOME_MSG: ${WELCOME_MSG}
      COLOR: ${COLOR}